### ISSUE TITLE
Multiple Instance RabbitMQ, Redis ..

### ISSUE THREAD

**Issue by ismlyldz** [jorgeacetozi/ebook-chat-app-spring-websocket-cassandra-redis#3]
I have a few questions?
Can rabbitmq be more than one? Do you have the chance to add an example of this? Can redis be more than one? Do you have the chance to add an example of this?

**Comment by jorgeacetozi** [comment]
`Chapter 12 - Multinode Chat Architecture` has the answer to your questions, which basically is: **all RabbitMQ, Redis, and Cassandra can run as clusters**.
Sorry, I can't add an example because this is out of the scope of the book. Running a highly-available solution for these tools requires a knowledge that is not covered in the book. However, you can easily find content online on these subjects, including the official docs for each of these tools, for example:
Redis: https://redis.io/topics/cluster-tutorial
RabbitMQ: https://www.rabbitmq.com/clustering.html
