### ISSUE TITLE
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)

### ISSUE THREAD

**Issue by vseveryn** [jorgeacetozi/ebook-chat-app-spring-websocket-cassandra-redis#4]
win10  

**docker-compose -f docker-compose/dependencies.yml up -d**  
Creating network "docker-compose_default" with the default driver  
Creating docker-compose_rabbitmq-stomp_1 ... done  
Creating docker-compose_cassandra_1      ... done
Creating docker-compose_redis_1          ... done
Creating docker-compose_mysql_1          ... done  

**java -jar ebook-chat-1.0.0.jar**
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)  

[mysql_error.txt](https://github.com/jorgeacetozi/ebook-chat-app-spring-websocket-cassandra-redis-rabbitmq/files/4000846/mysql_error.txt)

**Comment by jorgeacetozi** [comment]
Hi, sorry for the late response. Are you still having this issue?

**Comment by vseveryn** [comment]
I think yes, but I didn’t use it after I submitted an issue

**Comment by jorgeacetozi** [comment]
I see. From the exception, the application started in `dev` profile (which tries to establish a connection to MySQL using username `root` and password `root`) and the access was denied for these credentials. So, in theory, the only possibility is that the problem is in the MySQL container. I would advice you to debug the container by trying to connect to MySQL using a MySQL client, for example.
I've tested it here on Mac and Linux and it's working fine. You could also try to set up a Linux VM to see if this also happens there.

**Comment by vseveryn** [comment]
so far I managed to run it on my mac. windows is still to be investigated.

PS jar url in readme should be updated to https://github.com/jorgeacetozi/ebook-chat-app-spring-websocket-cassandra-redis-rabbitmq/releases/download/ebook-chat-1.0.0/ebook-chat-1.0.0.jar

**Comment by vseveryn** [comment]
I resolved my issue. The problem was in other mysql process running as windows service. Docker messages didn't show anything about such conflict.
